spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ckeditor_practice
    username: root
    password: p98j08w08#!@
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: create

  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 10MB
      max-request-size: 10MB
